name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '**'
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU for Docker Buildkit
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
            env.BUILDKIT_STEP_LOG_MAX_SPEED=-1
      - name: Run grub build (make ci)
        run: make ci
      # TODO: add signing
      - name: Upload onie-grubx64.efi
        uses: actions/upload-artifact@v3
        with:
          name: onie-grubx64.efi
          path: artifacts/onie-grubx64.efi
      - name: Upload sonic-grubx64.efi
        uses: actions/upload-artifact@v3
        with:
          name: sonic-grubx64.efi
          path: artifacts/sonic-grubx64.efi
      # TODO: add uploading of signed artifacts